name: Build PDF

on:
  push:
    branches: [main]
    paths: [cv.tex, Dockerfile]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create PDF file
        run: ./make_cv.sh
        shell: bash
      - name: Checkout github-pages branch
        uses: actions/checkout@v3
        with:
          ref: github-pages
          clean: false
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.1
        with:
          default_author: github_actions
          add: cv.pdf
          message: "docs: update pdf"
