name: Build PDF

on:
  push:
    branches: [main]
    paths: [cv.tex, Dockerfile]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build PDF file
        run: ./make_cv.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: cv.pdf
          if-no-files-found: error
          retention-days: 1
  commit-to-github-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout github-pages branch
        uses: actions/checkout@v3
        with:
          ref: github-pages
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: artifact
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.1
        with:
          default_author: github_actions
          add: cv.pdf
          message: "docs: update pdf"
